# Generated by Django 3.2.9 on 2022-01-02 21:04

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='agent_profile_picture',
            field=models.ImageField(blank=True, help_text='The agent picture', null=True, upload_to=account.models.upload_image_path),
        ),
    ]
