# Generated by Django 3.2.9 on 2021-12-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Single Room', 'Single Room'), ('Bouble Room', 'Bouble Room'), ('BedSitter', 'BedSitter'), ('1 Bedroom', '1 Bedroom'), ('2 Bedroom', '2 Bedroom'), ('3 Bedroom', '3 Bedroom'), ('4 Bedroom', '4 Bedroom')], help_text='The type of the room example single room', max_length=50),
        ),
    ]
