# Generated by Django 3.2.9 on 2021-12-16 05:28

from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_video',
            field=models.FileField(blank=True, help_text='The video of room ', null=True, upload_to=homepage.models.upload_image_path),
        ),
    ]
