# Generated by Django 3.2.9 on 2021-12-16 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_room_room_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='address',
            new_name='geom',
        ),
    ]
