# Generated by Django 3.2.9 on 2021-12-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_rename_address_building_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='description',
            field=models.TextField(blank=True, help_text='The description of the building', null=True),
        ),
    ]
