# Generated by Django 3.2.9 on 2022-02-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_bookingrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
