# Generated by Django 3.2.9 on 2022-02-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_room_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='payment_instructions',
            field=models.TextField(blank=True, help_text='Payment Instructions', null=True),
        ),
    ]
