# Generated by Django 3.2.9 on 2022-02-28 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_building_payment_instructions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapFrames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=255)),
                ('lng', models.CharField(max_length=255)),
                ('map_frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.mapframes')),
            ],
        ),
    ]
