# Generated by Django 3.2.9 on 2022-02-28 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_coordinated_mapframes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=255)),
                ('main_lat', models.CharField(max_length=255)),
                ('main_lng', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='coordinated',
            name='map_frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.maplocations'),
        ),
        migrations.DeleteModel(
            name='MapFrames',
        ),
    ]
