# Generated by Django 3.2.9 on 2022-02-28 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_rename_location_name_building_loc_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='loc_name',
        ),
        migrations.AddField(
            model_name='building',
            name='l_name',
            field=models.ForeignKey(blank=True, help_text='The location name of the building', null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.maplocations'),
        ),
        migrations.AddField(
            model_name='building',
            name='location_name',
            field=models.CharField(blank=True, help_text='The location name of the building', max_length=255, null=True),
        ),
    ]
