# Generated by Django 3.2.9 on 2022-02-28 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_auto_20220228_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='location_name',
        ),
    ]
